#!/bin/bash

###########################################
#                                         #
# cla-ssh: Command Line Assistant for SSH #
#                                         #
# Author:  Bryan T. Meyers                #
# Year:    2015                           #
# License: MIT                            #
#                                         #
###########################################

# Display Welcome Message
whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
	--title "Welcome to cla-ssh" \
	--msgbox "This tool will allow you to manage SSH keys in a safe, easy way.\n\n                      Let's get started!" \
	9 68

exitstatus=$?

# Run Multiple Times Until Quit
while [ $exitstatus = 0 ]; do

## Select an Operating Mode

MODE=$( whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
	--title "Pick a Task" \
	--cancel-button "Quit" \
	--menu "Choose From:" \
	12 68 5 \
	"Create" "Generate a New Key" \
	"Configure" "Change Settings for a Host" \
	"Replace" "Update an Existing Key" \
	"Remove" "Delete an Existing Key" \
	"Settings" "Configure cla-ssh" \
	3>&1 1>&2 2>&3 )

exitstatus=$?

if [ $exitstatus = 0 ]; then

case $MODE in
    "Create" )
        file="$HOME/.ssh/config"
        host="Host (\S*)"
        HOSTS=""
        while read line; do 
            if [[ $line =~ $host ]]; then
                HOSTS="$HOSTS${BASH_REMATCH[1]}//"
            fi
        done < $file
        oIFS="$IFS"
        IFS="/"
        CHOICE=$( whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
            --title "Select a Host" \
            --menu "" \
            12 68 5\
            "Add" "Add a new host" \
            ${HOSTS} \
	        3>&1 1>&2 2>&3 )
        IFS=$oIFS
        if [ $CHOICE = "Add" ]; then
            HOST=$( whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
                --title "Select a Host" \
                --inputbox "\nEnter a hostname:" \
                9 68 \
                3>&1 1>&2 2>&3 )
        else
            HOST=$CHOICE
        fi
        CIPHER=$( whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
            --title "Choose a Cipher" \
            --menu "" \
            12 68 5 \
            "ed25519" "Best" \
            "rsa" "Better" \
            "ecdsa" "Good" \
            "dsa" "Worse" \
            "rsa1" "Last Resort" \
            3>&1 1>&2 2>&3 )
        BITS=$( whiptail --backtitle "cla-ssh: Command Line Assistant for SSH" \
            --title "Choose a Key Length" \
            --inputbox "Pick a number greater than 2000, but less than 10000 (speed). The more random, the better." \
            9 68 \
            3>&1 1>&2 2>&3 )
        echo "HOST: $HOST"
        echo "CIPHER: $CIPHER"
        echo "BITS: $BITS"
        ;;
    "Configure" )
        ;;
    "Replace" )
        ;;
    "Remove" )
        ;;
    "Settings" )
        ;;
esac

fi

done
